#!/usr/bin/env node
/**
 * Convert Keras model (.keras) to TensorFlow.js format with uint8 quantization.
 * 
 * Usage:
 *   node scripts/convert-to-tfjs.mjs <input_model.keras> <output_dir> [--temperature=0.902] [--version=1.0.0] [--model-id=<id>]
 * 
 * Example:
 *   node scripts/convert-to-tfjs.mjs melanoma_v2_finetuning.keras demo/public/model/vgg16 --temperature=0.902 --version=1.0.0 --model-id=vgg16
 * 
 * Requirements:
 *   - TensorFlow.js Node: npm install @tensorflow/tfjs-node @tensorflow/tfjs-converter
 *   - Or run in Google Colab (see README)
 */

import { saveKerasModel } from '@tensorflow/tfjs-converter';
import * as tf from '@tensorflow/tfjs-node';
import { loadModel } from '@tensorflow/tfjs-node';
import fs from 'fs';
import path from 'path';

const args = process.argv.slice(2);
const inputPath = args[0];
const outputDir = args[1];
const temperatureArg = args.find(a => a.startsWith('--temperature='));
const versionArg = args.find(a => a.startsWith('--version='));
const modelIdArg = args.find(a => a.startsWith('--model-id='));

const TEMPERATURE = temperatureArg ? parseFloat(temperatureArg.split('=')[1]) : 0.902;
const VERSION = versionArg ? versionArg.split('=')[1] : '1.0.0';
const MODEL_ID = modelIdArg ? modelIdArg.split('=')[1] : 'custom';

if (!inputPath || !outputDir) {
  console.error('Usage: node scripts/convert-to-tfjs.mjs <input.keras> <output_dir> [--temperature=0.902] [--version=1.0.0] [--model-id=<id>]');
  process.exit(1);
}

if (!fs.existsSync(inputPath)) {
  console.error(`Input model not found: ${inputPath}`);
  process.exit(1);
}

async function convert() {
  console.log(`Loading Keras model from: ${inputPath}`);
  
  const model = await loadModel(`file://${path.resolve(inputPath)}`);
  
  console.log('\nModel Summary:');
  model.summary();
  
  fs.mkdirSync(outputDir, { recursive: true });
  
  console.log(`\nConverting to TF.js format with uint8 quantization...`);
  console.log(`Output directory: ${outputDir}`);
  console.log(`Metadata: temperature=${TEMPERATURE}, version=${VERSION}, modelId=${MODEL_ID}`);
  
  await saveKerasModel(model, `file://${path.resolve(outputDir)}`, {
    quantizationBytes: 1,
    userDefinedMetadata: {
      temperature: TEMPERATURE,
      version: VERSION,
      modelId: MODEL_ID,
      convertedAt: new Date().toISOString(),
    },
  });
  
  console.log('\n✅ Conversion complete!');
  console.log(`Model saved to: ${outputDir}`);
  console.log(`Files generated:`);
  fs.readdirSync(outputDir).forEach(f => {
    const stats = fs.statSync(path.join(outputDir, f));
    console.log(`  ${f} (${(stats.size / 1024 / 1024).toFixed(2)} MB)`);
  });
  
  const modelJsonPath = path.join(outputDir, 'model.json');
  const modelJson = JSON.parse(fs.readFileSync(modelJsonPath, 'utf8'));
  console.log(`\nModel format: ${modelJson.format}`);
  console.log(`Generated by: ${modelJson.convertedBy}`);
  console.log(`User metadata:`, modelJson.userDefinedMetadata);
}

convert().catch(err => {
  console.error('\n❌ Conversion failed:', err);
  process.exit(1);
});
