#!/usr/bin/env node
/**
 * Convert Keras model (.keras) to TensorFlow.js format with uint8 quantization.
 * 
 * Usage:
 *   node scripts/convert-to-tfjs.mjs <input_model.keras> <output_dir> [--temperature=0.902] [--version=1.0.0]
 * 
 * Example:
 *   node scripts/convert-to-tfjs.mjs melanoma_v2_finetuning.keras demo/public/model --temperature=0.902 --version=1.0.0
 * 
 * Requirements:
 *   - TensorFlow.js Node: npm install @tensorflow/tfjs-node @tensorflow/tfjs-converter
 *   - Or run in Google Colab (see README)
 */

import { saveKerasModel } from '@tensorflow/tfjs-converter';
import * as tf from '@tensorflow/tfjs-node';
import { loadModel } from '@tensorflow/tfjs-node';
import fs from 'fs';
import path from 'path';

const args = process.argv.slice(2);
const inputPath = args[0];
const outputDir = args[1];
const temperatureArg = args.find(a => a.startsWith('--temperature='));
const versionArg = args.find(a => a.startsWith('--version='));

const TEMPERATURE = temperatureArg ? parseFloat(temperatureArg.split('=')[1]) : 0.902;
const VERSION = versionArg ? versionArg.split('=')[1] : '1.0.0';

if (!inputPath || !outputDir) {
  console.error('Usage: node scripts/convert-to-tfjs.mjs <input_model.keras> <output_dir> [--temperature=0.902] [--version=1.0.0]');
  process.exit(1);
}

if (!fs.existsSync(inputPath)) {
  console.error(`Input model not found: ${inputPath}`);
  process.exit(1);
}

async function convert() {
  console.log(`Loading Keras model from: ${inputPath}`);
  
  // Load the Keras model
  const model = await loadModel(`file://${path.resolve(inputPath)}`);
  
  // Print model summary for verification
  console.log('\nModel Summary:');
  model.summary();
  
  // Ensure output directory exists
  fs.mkdirSync(outputDir, { recursive: true });
  
  console.log(`\nConverting to TF.js format with uint8 quantization...`);
  console.log(`Output directory: ${outputDir}`);
  console.log(`Embedding metadata: temperature=${TEMPERATURE}, version=${VERSION}`);
  
  // Convert and save with uint8 quantization + user metadata
  // This reduces model size ~4x (from ~84MB to ~15MB)
  await saveKerasModel(model, `file://${path.resolve(outputDir)}`, {
    quantizationBytes: 1,  // uint8 quantization
    userDefinedMetadata: {
      temperature: TEMPERATURE,
      version: VERSION,
      convertedAt: new Date().toISOString(),
    },
  });
  
  console.log('\n✅ Conversion complete!');
  console.log(`Model saved to: ${outputDir}`);
  console.log(`Files generated:`);
  fs.readdirSync(outputDir).forEach(f => {
    const stats = fs.statSync(path.join(outputDir, f));
    console.log(`  ${f} (${(stats.size / 1024 / 1024).toFixed(2)} MB)`);
  });
  
  // Verify the model.json has the right structure
  const modelJsonPath = path.join(outputDir, 'model.json');
  const modelJson = JSON.parse(fs.readFileSync(modelJsonPath, 'utf8'));
  console.log(`\nModel format: ${modelJson.format}`);
  console.log(`Generated by: ${modelJson.convertedBy}`);
  console.log(`Model topology type: ${modelJson.modelTopologyType || 'graph'}`);
  console.log(`User metadata:`, modelJson.userDefinedMetadata);
}

convert().catch(err => {
  console.error('\n❌ Conversion failed:', err);
  process.exit(1);
});